name: "SPFx CICD"
description: "Build, bundle, package, test, and deploy SPFx solution"
on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI-SPFx:
    runs-on: ubuntu-latest
    steps:
      - name: Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Run npm ci
        run: npm ci

      - name: Build
        run: gulp build

      - name: Test
        run: npm test

      - name: Bundle and package
        run: |
          gulp bundle --ship
          gulp package-solution --ship

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sppkg-files
          path: "**/*.sppkg"
          if-no-files-found: error

  CD-SPFx:
    runs-on: ubuntu-latest
    environment: Production
    if: github.event_name == 'push'
    needs: CI-SPFx
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: sppkg-files

      - name: Install PnP CLI M365
        run: sudo npm install --global @pnp/cli-microsoft365

      - name: Login to M365 CLI
        run: m365 login --authType password --userName ${{ secrets.M365_USERNAME }} --password ${{ secrets.M365_PASSWORD }}

      - name: Upload SPFx to Collection
        run: m365 spo app add --filePath ./hello_world --appCatalogUrl "https://infoqo.sharepoint.com/sites/POSTPAMDEV/AppCatalog/Forms/AllItems.aspx" --scope "https://infoqo.sharepoint.com/sites/POSTPAMDEV/" --overwrite

      - name: Deploy SPFx package
        run: m365 spo app deploy --name ${{ env.ApplicationcustomizerfirstApplicationCustomizer }} --appCatalogUrl "https://infoqo.sharepoint.com/sites/POSTPAMDEV/AppCatalog/Forms/AllItems.aspx" --scope "https://infoqo.sharepoint.com/sites/POSTPAMDEV/"
